### ISSUE TITLE
Fabric ThreatenGL need Architectury at 1.3.1-beta1

### ISSUE THREAD

**Issue by KITE2459** [Numelon-Softworks/ThreatenGL#10]
I used threatengl 1.2.1-beta3 in fabric
after seeing 1.3.1-beta1 that came up today, so installed it.
and then The following crash report appears.

I installed the architecture API after viewing the crash report, and it ran normally
[crash-2024-05-20_13.12.24-client.txt](https://github.com/Numelon-Softworks/ThreatenGL/files/15372839/crash-2024-05-20_13.12.24-client.txt)

![image](https://github.com/Numelon-Softworks/ThreatenGL/assets/119291913/bfe07c9f-0659-4567-8f94-318d3527a1f5)

**Comment by Richy-Z** [comment]
Good Afternoon, @KITE2459 ☀️ 
I hope you're having a wonderful day. I've reviewed your crash report and yes - it does seem like the crash was due to the Architectury API missing on Fabric.
This is because in 1.3.1-beta.1, client/server checking was implemented in order prevent this mod from being run on the server side and subsequently prevent unnecessary GitHub issues from being created because one may not have known that this was a client side mod only. However, as you've noticed yourself, this is causing dependency issues as the common code now relies on Architectury mappings to check which side the mod is running on.
For obvious reasons, it is completely unreasonable for this mod to require another dependency which may potentially break other mods (as noted in a different issue) considering its basic functions.

The next iteration of ThreatenGL will either:
a) remove the client/server checking functionality entirely and rely solely on the mod configuration files (`mods.toml` and `mod.json`) to ensure it doesn't run on servers and runs only on the client
b) Remove the feature from the common code and implement it per-platform (code duplication but with different mappings, slightly different code, same functionality)

Thank you for reporting this issue! 😊

**Comment by Richy-Z** [comment]
Hello again!
This dependency issue has been completely fixed, and great news - ThreatenGL now requires **absolutely no dependencies**! This means that QFAPI and the Architectury API are no longer required on any mod loader in order to use this mod. 🤩

ThreatenGL 1.3.2 (Beta 1) will be available to download from Modrinth in an hour. 😁
https://modrinth.com/mod/threatengl

**Comment by KITE2459** [comment]
Thank you, i read it now
I'm using 1.3.2 beta 1 well
