### ISSUE TITLE
NeoForge marks it as incompatible, which prevents further load

### ISSUE THREAD

**Issue by Hekzory** [Numelon-Softworks/ThreatenGL#7]
So, launching it on NeoForge 1.20.6 is not supported or at least it is what neoforge says.

Neoforge version is 20.6.72-beta. Probably they changed incompatibility detection or something like that in newer versions.

![image](https://github.com/Numelon-Softworks/ThreatenGL/assets/36638457/07069a81-7ea2-4d34-a8aa-c58c487043bc)

In logs there is just one line about the mod: 
`[19May2024 01:02:04.622] [main/WARN] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found incompatible jar C:\Users\******\AppData\Roaming\PrismLauncher\instances\1.20.6\minecraft\mods\threatengl-neoforge-1.2.1-beta.3.jar with reason MINECRAFT_FORGE. Skipping.`

Also, a bit offtopic(probably) question about the core functionality, just not to make a separate issue. Am I right to assume that Embeddium(Sodium) already requests OpenGL 4.6 where possible? At least it looks like the latest OpenGL version is already requested in the logs even without the mod loaded. Or does this mod help with loading latest OpenGL even further on some devices?

**Comment by Richy-Z** [comment]
Hi!

Thanks for reporting the issue - I'll look into this strange error. NeoForge did work before, so it's possible something changed in the newer versions.

Regarding the question, you're partially correct about other mods (especially performance mods related to graphics) and them trying to do something with OpenGL. If I recall correctly, the logs from Sodium check the **capabilities** of the hardware rather than explicitly setting the OpenGL version.

OpenGL's versioning can be quite confusing, especially considering the fact that it can be *forward-compatible*. This means that even if Minecraft is initialised with an OpenGL 3.2 context, a mod could potentially still use features that are present in OpenGL 4.6, provided the driver and hardware support those features. However, a thing that should be noted is that although OpenGL allows for forward compatibility, the extent to which this is practical can depend heavily on your GPU driver and the manufacturer's implementation of the OpenGL specification.

Some drivers may not expose newer features through older contexts, even if the hardware supports them. This is due to driver-specific limitations and optimisations that may require initialising a context with a newer OpenGL version in order to fully access all features and performance benefits. Here are some examples of this:
- **Some** NVIDIA GPU Drivers seem to intentionally disable the exposure of the latest OpenGL capabilities when running on a legacy context version, likely for performance optimisations and to maintain strict backwards compatibility (e.g. If an OpenGL 3.2 context was created, then some OpenGL 4.6 features wouldn't be available, despite OpenGL's **forward compatibility** feature).
- Another example is with some older AMD GPU drivers on Windows, where the drivers were not enabling OpenGL 4.5+ features on GCN 1.0 and 1.1 hardware (e.g. AMD Radeon R9 290 series) when creating a context at version 4.4 or lower, even though the hardware supports the features, although... updating to the latest drivers often resolved this limitation or bug.
So although the OpenGL specification mandates enabling all the features from the requested version by default, GPU vendors such as like NVIDIA and AMD have historically taken some liberties with older drivers to disable newer capabilities in legacy contexts as an optimisation trade-off (or for other reasons).

Nevertheless, it is clear from just those two examples alone that OpenGL, the implementation of the specification by manufacturers, the drivers, and the use of OpenGL by developers such as in Minecraft are all a bit fuzzy. Therefore, the purpose of ThreatenGL is as follows:
- To push Minecraft away from the OpenGL 3.2 Specification, which is 16 years old by now
- To ensure that Minecraft **explicitly requests** the highest supported version of OpenGL right from the start, guaranteeing that all available features and optimisations provided by the driver upon requesting a higher OpenGL version are utilised
- To potentially help in improving performance and stability, especially on systems with newer hardware that supports OpenGL 4.6
- To eliminate the past issues that I described previously in the two examples, and maybe to even eliminate future similar bugs in drivers
- And finally, although this isn't highly significant, it ensures the correct OpenGL version is displayed when pressing F3. Why hide under OpenGL version 3.2 when some Minecraft mods clearly use OpenGL 4.6 features?

Thanks again for your feedback, and let me know if you have any more questions or need further assistance! 😁
I've updated ThreatenGL and a new version should be live on Modrinth in a few minutes.

**Comment by Richy-Z** [comment]
This issue has been resolved in ThreatenGL 1.3.0-*, however, that will be skipped and ThreatenGL 1.3.1-beta.1 will be uploaded to Modrinth instead because of another feature added on such a short notice.

The latest version of ThreatenGL will be available on Modrinth in a few minutes 😊

I'd like to close this issue, but I will keep it open for 1 or 2 days incase you have any further questions about the core functionality of ThreatenGL. 👍

**Comment by Richy-Z** [comment]
Hi again,
This issue will be closed now as I see you have not responded with any further questions. 😶
All the issues you have outlined have been fixed in ThreatenGL 1.3.2 (Beta 1) and also, great news - you no longer require any additional libraries/mods in order to run ThreatenGL!

ThreatenGL 1.3.2 (Beta 1) will be available to download from Modrinth in an hour. 😁
https://modrinth.com/mod/threatengl

If you have any further questions about the core functionality of this mod, please join the Discord for discussion:
https://discord.gg/eYEDsnKh2T

Have a great evening! 🌇
