### ISSUE TITLE
the need for a mod with existing GL 4.6 support and incompatibilities

### ISSUE THREAD

**Issue by xboct02** [Numelon-Softworks/ThreatenGL#9]
Does the mod really contain improvements with Open GL 4.6? Some mods, including the fabric api, do not work with qfapi, the fabric api is incompatible with Threatengl. A vicious circle that forces you to abandon mods incompatible with qfapi for the sake of Threatengl

**Comment by Richy-Z** [comment]
Hello!
Regarding the compatibility with other mods, ThreatenGL should have been compatible with every other mod until 1.3.1-beta.1 was released with some breaking changes, which will be reverted accordingly. After this fix, you will be able to use ThreatenGL again without the Architectury API and without causing incompatibility issues with other mods.

> Does the mod really contain improvements with OpenGL 4.6?

Regarding this and the core functionality of the mod, you can view an answer I provided previously to a similar question in a different issue: https://github.com/Numelon-Softworks/ThreatenGL/issues/7#issuecomment-2119318566

I hope this helps! 😁

**Comment by Richy-Z** [comment]
Hi!
ThreatenGL has been heavily modified in order to reduce dependence on the Architectury API for Forge and QSL/QFAPI for Quilt, solving the issues you outlined. ThreatenGL now requires absolutely no dependencies, which increases mod compatibility and reduces the possibility of mod conflicts. 😍

ThreatenGL 1.3.2 (Beta 1) will be available to download from Modrinth in an hour. 😁
https://modrinth.com/mod/threatengl

If you have any further questions about the core functionality of this mod, please join the Discord for discussion:
https://discord.gg/eYEDsnKh2T

Have a great evening! 🌇
